#!/bin/sh
if [ -z $3 ]; then
    echo "usage: ./install <rule_hashsize> <peer_hashsize> <the_secret>" 
    exit 1
fi

make && make install && depmod -ae && insmod ./ipt_pknock.ko rule_hashsize=$1 peer_hashsize=$2 secret=$3
