#!/bin/sh
if [ -z $1 ]; then
    echo "You must specify <rule_hashsize>"
    exit 1
fi

if [ -z $2 ]; then
    echo "You must specify <peer_hashsize>"
    exit 1
fi

make clean && make && make install && depmod -ae && insmod ./ipt_pknock.ko rule_hashsize=$1 peer_hashsize=$2
